export default
{
	rules :
	{
		// https://eslint.org/docs/latest/rules/
		
		///////////////////////
		// Possible Problems //
		///////////////////////
		"array-callback-return"           : 2,
		"constructor-super"               : 2,
		"for-direction"                   : 2,
		"getter-return"                   : 0,
		"no-async-promise-executor"       : 2,
		"no-await-in-loop"                : 0,
		"no-class-assign"                 : 2,
		"no-compare-neg-zero"             : 2,
		"no-cond-assign"                  : [2, "always"],
		"no-const-assign"                 : 2,
		"no-constant-binary-expression"   : 2,
		"no-constant-condition"           : [2, {"checkLoops" : false}],
		"no-constructor-return"           : 2,
		"no-control-regex"                : 2,
		"no-debugger"                     : 2,
		"no-dupe-args"                    : 2,
		"no-dupe-class-members"           : 2,
		"no-dupe-else-if"                 : 2,
		"no-dupe-keys"                    : 2,
		"no-duplicate-case"               : 2,
		"no-duplicate-imports"            : 2,
		"no-empty-character-class"        : 2,
		"no-empty-pattern"                : 2,
		"no-ex-assign"                    : 2,
		"no-fallthrough"                  : 2,
		"no-func-assign"                  : 2,
		"no-import-assign"                : 2,
		"no-inner-declarations"           : [2, "functions"],
		"no-invalid-regexp"               : 2,
		"no-irregular-whitespace"         : [2, {"skipStrings" : true, "skipTemplates" : true}],
		"no-loss-of-precision"            : 2,
		"no-misleading-character-class"   : 2,
		"no-new-native-nonconstructor"    : 2,
		"no-obj-calls"                    : 2,
		"no-promise-executor-return"      : 2,
		"no-prototype-builtins"           : 0,
		"no-self-assign"                  : 2,
		"no-self-compare"                 : 2,
		"no-setter-return"                : 2,
		"no-sparse-arrays"                : 2,
		"no-template-curly-in-string"     : 2,
		"no-this-before-super"            : 2,
		"no-undef"                        : [2, {"typeof" : true}],
		"no-unexpected-multiline"         : 2,
		"no-unmodified-loop-condition"    : 2,
		"no-unreachable"                  : 2,
		"no-unreachable-loop"             : 2,
		"no-unsafe-finally"               : 2,
		"no-unsafe-negation"              : 2,
		"no-unsafe-optional-chaining"     : 2,
		"no-unused-private-class-members" : 2,
		"no-unused-vars"                  : [2, {"caughtErrors" : "all", "argsIgnorePattern" : "^[iI]gnored$|^e$|^xlog$|^_", "varsIgnorePattern" : "^XU|xu|xlog$" }],
		"no-use-before-define"            : [2, {"functions" : false}],
		"no-useless-assignment"           : 2,
		"no-useless-backreference"        : 2,
		"require-atomic-updates"          : 0,	// Lots of false positives
		"use-isnan"                       : 2,
		"valid-typeof"                    : 2,

		/////////////////
		// Suggestions //
		/////////////////
		"accessor-pairs"                 : 0,
		"arrow-body-style"               : [2, "as-needed"],
		"block-scoped-var"               : 2,
		"camelcase"                      : [2, {properties : "always"}],
		"capitalized-comments"           : 0,
		"class-methods-use-this"         : 0,
		"complexity"                     : 0,
		"consistent-return"              : 0,
		"consistent-this"                : [2, "self"],
		"curly"                          : [2, "multi-or-nest", "consistent"],
		"default-case"                   : 0,
		"default-case-last"              : 2,
		"default-param-last"             : 0,
		"dot-notation"                   : [2, {"allowKeywords" : true}],
		"eqeqeq"                         : [2, "always"],
		"func-name-matching"             : 0,
		"func-names"                     : [2, "as-needed"],
		"func-style"                     : 0,
		"grouped-accessor-pairs"         : 2,
		"guard-for-in"                   : 2,
		"id-denylist"                    : 0,
		"id-length"                      : 0,
		"id-match"                       : 0,
		"init-declarations"              : 0,
		"logical-assignment-operators"   : [2, "always", {"enforceForIfStatements" : true}],
		"max-classes-per-file"           : 0,
		"max-depth"                      : [2, 10],
		"max-lines"                      : 0,
		"max-lines-per-function"         : 0,
		"max-nested-callbacks"           : [2, 5],
		"max-params"                     : [2, 9],
		"max-statements"                 : 0,
		"new-cap"                        : 2,
		"no-alert"                       : 2,
		"no-array-constructor"           : 2,
		"no-bitwise"                     : 2,
		"no-caller"                      : 2,
		"no-case-declarations"           : 2,
		"no-console"                     : 0,
		"no-continue"                    : 0,
		"no-delete-var"                  : 2,
		"no-div-regex"                   : 2,
		"no-else-return"                 : 2,
		"no-empty"                       : [2, {"allowEmptyCatch" : true}],
		"no-empty-function"              : 0,
		"no-empty-static-block"          : 2,
		"no-eq-null"                     : 2,
		"no-eval"                        : 2,
		"no-extend-native"               : 0,
		"no-extra-bind"                  : 2,
		"no-extra-boolean-cast"          : 2,
		"no-extra-label"                 : 2,
		"no-global-assign"               : 2,
		"no-implicit-coercion"           : 0,
		"no-implicit-globals"            : 2,
		"no-implied-eval"                : 2,
		"no-inline-comments"             : 0,
		"no-invalid-this"                : 0,
		"no-iterator"                    : 2,
		"no-label-var"                   : 2,
		"no-labels"                      : 2,
		"no-lone-blocks"                 : 2,
		"no-lonely-if"                   : 0,	// Handled better by unicorn/no-lonely-if
		"no-loop-func"                   : 2,
		"no-magic-numbers"               : 0,
		"no-multi-assign"                : 0,
		"no-multi-str"                   : 2,
		"no-negated-condition"           : 0,
		"no-nested-ternary"              : 0,
		"no-new"                         : 2,
		"no-new-func"                    : 2,
		"no-new-wrappers"                : 2,
		"no-nonoctal-decimal-escape"     : 2,
		"no-object-constructor"          : 2,
		"no-octal"                       : 2,
		"no-octal-escape"                : 2,
		"no-param-reassign"              : 0,
		"no-plusplus"                    : 0,
		"no-proto"                       : 2,
		"no-redeclare"                   : 2,
		"no-regex-spaces"                : 2,
		"no-restricted-exports"          : 0,
		"no-restricted-globals"          : 0,
		"no-restricted-imports"          : 0,
		"no-restricted-properties"       : 0,
		"no-restricted-syntax"           : 0,
		"no-return-assign"               : 2,
		"no-script-url"                  : 2,
		"no-sequences"                   : 0,
		"no-shadow"                      : 2,
		"no-shadow-restricted-names"     : 2,
		"no-ternary"                     : 0,
		"no-throw-literal"               : 2,
		"no-undef-init"                  : 0,
		"no-undefined"                   : 0,
		"no-underscore-dangle"           : [0],
		"no-unneeded-ternary"            : 2,
		"no-unused-expressions"          : [2, {allowTaggedTemplates : true, allowTernary : true}],
		"no-unused-labels"               : 2,
		"no-useless-call"                : 2,
		"no-useless-catch"               : 2,
		"no-useless-computed-key"        : 2,
		"no-useless-concat"              : 2,
		"no-useless-constructor"         : 2,
		"no-useless-escape"              : 2,
		"no-useless-rename"              : 0,
		"no-useless-return"              : 2,
		"no-var"                         : 2,
		"no-void"                        : 2,
		"no-warning-comments"            : 1,
		"no-with"                        : 2,
		"object-shorthand"               : [2, "always"],
		"one-var"                        : 0,
		"operator-assignment"            : 0,
		"prefer-arrow-callback"          : [2, {"allowNamedFunctions" : true}],
		"prefer-const"                   : 2,
		"prefer-destructuring"           : 0,	// We have our own prefer-object-destructuring which behaves more how I want it to
		"prefer-exponentiation-operator" : 2,
		"prefer-named-capture-group"     : 0,
		"prefer-numeric-literals"        : 2,
		"prefer-object-has-own"          : 2,
		"prefer-object-spread"           : 0,
		"prefer-promise-reject-errors"   : 0,
		"prefer-regex-literals"          : 0,
		"prefer-rest-params"             : 2,
		"prefer-spread"                  : 2,
		"prefer-template"                : 2,
		"radix"                          : 2,
		"require-await"                  : 2,
		"require-unicode-regexp"         : 0,
		"require-yield"                  : 2,
		"sort-imports"                   : 0,
		"sort-keys"                      : 0,
		"sort-vars"                      : 0,
		"strict"                         : 0,
		"symbol-description"             : 0,
		"vars-on-top"                    : 2,
		"yoda"                           : 2,

		/////////////////////////
		// Layout & Formatting //
		/////////////////////////
		"unicode-bom" : 0
	}
};
