import sonarjs from "eslint-plugin-sonarjs";

export default
{
	plugins :
	{
		sonarjs
	},
	rules :
	{
		// https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/README.md#rules
		"sonarjs/anchor-precedence"                    : 2,
		"sonarjs/argument-type"                        : 2,
		"sonarjs/arguments-order"                      : 2,
		"sonarjs/arguments-usage"                      : 0,
		"sonarjs/array-callback-without-return"        : 2,
		"sonarjs/array-constructor"                    : 0,	// handled by unicorn/no-new-array
		"sonarjs/arrow-function-convention"            : 2,
		"sonarjs/assertions-in-tests"                  : 0,
		"sonarjs/aws-apigateway-public-api"            : 0,
		"sonarjs/aws-ec2-rds-dms-public"               : 0,
		"sonarjs/aws-ec2-unencrypted-ebs-volume"       : 0,
		"sonarjs/aws-efs-unencrypted"                  : 0,
		"sonarjs/aws-iam-all-privileges"               : 0,
		"sonarjs/aws-iam-all-resources-accessible"     : 0,
		"sonarjs/aws-iam-privilege-escalation"         : 0,
		"sonarjs/aws-iam-public-access"                : 0,
		"sonarjs/aws-opensearchservice-domain"         : 0,
		"sonarjs/aws-rds-unencrypted-databases"        : 0,
		"sonarjs/aws-restricted-ip-admin-access"       : 0,
		"sonarjs/aws-s3-bucket-granted-access"         : 0,
		"sonarjs/aws-s3-bucket-insecure-http"          : 0,
		"sonarjs/aws-s3-bucket-public-access"          : 0,
		"sonarjs/aws-s3-bucket-versioning"             : 0,
		"sonarjs/aws-sagemaker-unencrypted-notebook"   : 0,
		"sonarjs/aws-sns-unencrypted-topics"           : 0,
		"sonarjs/aws-sqs-unencrypted-queue"            : 0,
		"sonarjs/bitwise-operators"                    : 2,
		"sonarjs/block-scoped-var"                     : 2,
		"sonarjs/bool-param-default"                   : 0,	// typescript
		"sonarjs/call-argument-line"                   : 0,
		"sonarjs/chai-determinate-assertion"           : 0,
		"sonarjs/class-name"                           : 0,
		"sonarjs/class-prototype"                      : 0,
		"sonarjs/code-eval"                            : 0,
		"sonarjs/cognitive-complexity"                 : 0,
		"sonarjs/comma-or-logical-or-case"             : 2,
		"sonarjs/comment-regex"                        : 0,
		"sonarjs/concise-regex"                        : 2,
		"sonarjs/confidential-information-logging"     : 0,
		"sonarjs/constructor-for-side-effects"         : 2,
		"sonarjs/content-length"                       : 0,
		"sonarjs/content-security-policy"              : 0,
		"sonarjs/cookie-no-httponly"                   : 0,
		"sonarjs/cors"                                 : 0,
		"sonarjs/csrf"                                 : 0,
		"sonarjs/cyclomatic-complexity"                : 0,
		"sonarjs/declarations-in-global-scope"         : 0,
		"sonarjs/deprecation"                          : 2,
		"sonarjs/destructuring-assignment-syntax"      : 2,
		"sonarjs/different-types-comparison"           : 2,
		"sonarjs/disabled-auto-escaping"               : 0,
		"sonarjs/disabled-resource-integrity"          : 0,
		"sonarjs/disabled-timeout"                     : 0,
		"sonarjs/duplicates-in-character-class"        : 2,
		"sonarjs/elseif-without-else"                  : 0,
		"sonarjs/empty-string-repetition"              : 2,
		"sonarjs/encryption-secure-mode"               : 0,
		"sonarjs/existing-groups"                      : 2,
		"sonarjs/expression-complexity"                : 0,
		"sonarjs/file-header"                          : 0,
		"sonarjs/file-name-differ-from-class"          : 0,
		"sonarjs/file-permissions"                     : 0,
		"sonarjs/file-uploads"                         : 0,
		"sonarjs/fixme-tag"                            : 1,
		"sonarjs/for-in"                               : 0,
		"sonarjs/for-loop-increment-sign"              : 2,
		"sonarjs/frame-ancestors"                      : 0,
		"sonarjs/function-inside-loop"                 : 2,
		"sonarjs/function-name"                        : 0,
		"sonarjs/function-return-type"                 : 2,
		"sonarjs/future-reserved-words"                : 2,
		"sonarjs/generator-without-yield"              : 2,
		"sonarjs/hashing"                              : 0,
		"sonarjs/hidden-files"                         : 0,
		"sonarjs/in-operator-type-error"               : 2,
		"sonarjs/inconsistent-function-call"           : 2,
		"sonarjs/index-of-compare-to-positive-number"  : 2,
		"sonarjs/insecure-cookie"                      : 0,
		"sonarjs/insecure-jwt-token"                   : 0,
		"sonarjs/inverted-assertion-arguments"         : 2,
		"sonarjs/jsx-no-leaked-render"                 : 0,
		"sonarjs/label-position"                       : 0,
		"sonarjs/link-with-target-blank"               : 0,
		"sonarjs/max-lines-per-function"               : 0,
		"sonarjs/max-lines"                            : 0,
		"sonarjs/max-switch-cases"                     : [2, 20],
		"sonarjs/max-union-size"                       : 0,
		"sonarjs/misplaced-loop-counter"               : 2,
		"sonarjs/nested-control-flow"                  : [2, {maximumNestingLevel : 10}],
		"sonarjs/new-operator-misuse"                  : 0,
		"sonarjs/no-all-duplicated-branches"           : 2,
		"sonarjs/no-alphabetical-sort"                 : 2,
		"sonarjs/no-angular-bypass-sanitization"       : 0,
		"sonarjs/no-array-delete"                      : 2,
		"sonarjs/no-associative-arrays"                : 2,
		"sonarjs/no-async-constructor"                 : 2,
		"sonarjs/no-built-in-override"                 : 2,
		"sonarjs/no-case-label-in-switch"              : 2,
		"sonarjs/no-clear-text-protocols"              : 0,
		"sonarjs/no-code-after-done"                   : 0,
		"sonarjs/no-collapsible-if"                    : 2,
		"sonarjs/no-collection-size-mischeck"          : 0,
		"sonarjs/no-commented-code"                    : 0,
		"sonarjs/no-control-regex"                     : 0,	// handled elsewhere
		"sonarjs/no-dead-store"                        : 2,
		"sonarjs/no-delete-var"                        : 2,
		"sonarjs/no-duplicate-in-composite"            : 0,	// typescript
		"sonarjs/no-duplicate-string"                  : 0,
		"sonarjs/no-duplicated-branches"               : 2,
		"sonarjs/no-element-overwrite"                 : 2,
		"sonarjs/no-empty-after-reluctant"             : 2,
		"sonarjs/no-empty-alternatives"                : 2,
		"sonarjs/no-empty-character-class"             : 2,
		"sonarjs/no-empty-collection"                  : 2,
		"sonarjs/no-empty-group"                       : 2,
		"sonarjs/no-empty-test-file"                   : 0,
		"sonarjs/no-equals-in-for-termination"         : 0,
		"sonarjs/no-exclusive-tests"                   : 0,
		"sonarjs/no-extra-arguments"                   : 2,
		"sonarjs/no-fallthrough"                       : 0,
		"sonarjs/no-for-in-iterable"                   : 2,
		"sonarjs/no-function-declaration-in-block"     : 0,
		"sonarjs/no-global-this"                       : 0,
		"sonarjs/no-globals-shadowing"                 : 0,
		"sonarjs/no-gratuitous-expressions"            : 2,
		"sonarjs/no-hardcoded-ip"                      : 0,
		"sonarjs/no-hardcoded-passwords"               : 0,
		"sonarjs/no-hardcoded-secrets"                 : 0,
		"sonarjs/no-hook-setter-in-body"               : 0,
		"sonarjs/no-identical-conditions"              : 2,
		"sonarjs/no-identical-expressions"             : 2,
		"sonarjs/no-identical-functions"               : 0,
		"sonarjs/no-ignored-exceptions"                : 2,
		"sonarjs/no-ignored-return"                    : 0,
		"sonarjs/no-implicit-dependencies"             : 0,	// typescript
		"sonarjs/no-implicit-global"                   : 2,
		"sonarjs/no-in-misuse"                         : 2,
		"sonarjs/no-incomplete-assertions"             : 0,
		"sonarjs/no-inconsistent-returns"              : 0,	// gave error when set to 2
		"sonarjs/no-incorrect-string-concat"           : 2,
		"sonarjs/no-internal-api-use"                  : 2,
		"sonarjs/no-intrusive-permissions"             : 0,
		"sonarjs/no-invalid-await"                     : 2,
		"sonarjs/no-invalid-regexp"                    : 2,
		"sonarjs/no-invariant-returns"                 : 0,
		"sonarjs/no-inverted-boolean-check"            : 2,
		"sonarjs/no-ip-forward"                        : 0,
		"sonarjs/no-labels"                            : 0,
		"sonarjs/no-literal-call"                      : 2,
		"sonarjs/no-mime-sniff"                        : 0,
		"sonarjs/no-misleading-array-reverse"          : 2,
		"sonarjs/no-misleading-character-class"        : 2,
		"sonarjs/no-mixed-content"                     : 0,
		"sonarjs/no-nested-assignment"                 : 2,
		"sonarjs/no-nested-conditional"                : 0,
		"sonarjs/no-nested-functions"                  : 0,
		"sonarjs/no-nested-incdec"                     : 0,
		"sonarjs/no-nested-switch"                     : 2,
		"sonarjs/no-nested-template-literals"          : 0,
		"sonarjs/no-one-iteration-loop"                : 2,
		"sonarjs/no-os-command-from-path"              : 0,
		"sonarjs/no-parameter-reassignment"            : 2,
		"sonarjs/no-primitive-wrappers"                : 2,
		"sonarjs/no-redundant-assignments"             : 2,
		"sonarjs/no-redundant-boolean"                 : 2,
		"sonarjs/no-redundant-jump"                    : 2,
		"sonarjs/no-redundant-optional"                : 0,	// typescript
		"sonarjs/no-reference-error"                   : 2,
		"sonarjs/no-referrer-policy"                   : 0,
		"sonarjs/no-regex-spaces"                      : 2,
		"sonarjs/no-require-or-define"                 : 0,
		"sonarjs/no-return-type-any"                   : 0,	// typescript
		"sonarjs/no-same-argument-assert"              : 0,
		"sonarjs/no-same-line-conditional"             : 2,
		"sonarjs/no-selector-parameter"                : 2,
		"sonarjs/no-skipped-tests"                     : 0,
		"sonarjs/no-small-switch"                      : 2,
		"sonarjs/no-sonar-comments"                    : 0,
		"sonarjs/no-table-as-layout"                   : 0,
		"sonarjs/no-try-promise"                       : 2,
		"sonarjs/no-undefined-argument"                : 0,	// typescript
		"sonarjs/no-undefined-assignment"              : 0,
		"sonarjs/no-unenclosed-multiline-block"        : 2,
		"sonarjs/no-uniq-key"                          : 0,
		"sonarjs/no-unsafe-unzip"                      : 0,
		"sonarjs/no-unthrown-error"                    : 2,
		"sonarjs/no-unused-collection"                 : 2,
		"sonarjs/no-unused-function-argument"          : 0,
		"sonarjs/no-unused-vars"                       : 0,	// handled elsewhere
		"sonarjs/no-use-of-empty-return-value"         : 2,
		"sonarjs/no-useless-catch"                     : 2,
		"sonarjs/no-useless-increment"                 : 2,
		"sonarjs/no-useless-intersection"              : 0,	// typescript
		"sonarjs/no-useless-react-setstate"            : 0,
		"sonarjs/no-variable-usage-before-declaration" : 2,
		"sonarjs/no-weak-cipher"                       : 0,
		"sonarjs/no-weak-keys"                         : 0,
		"sonarjs/no-wildcard-import"                   : 0,
		"sonarjs/non-existent-operator"                : 2,
		"sonarjs/non-number-in-arithmetic-expression"  : 2,
		"sonarjs/null-dereference"                     : 2,
		"sonarjs/object-alt-content"                   : 0,
		"sonarjs/operation-returning-nan"              : 2,
		"sonarjs/os-command"                           : 0,
		"sonarjs/post-message"                         : 0,
		"sonarjs/prefer-default-last"                  : 2,
		"sonarjs/prefer-immediate-return"              : 2,
		"sonarjs/prefer-object-literal"                : 0,
		"sonarjs/prefer-promise-shorthand"             : 2,
		"sonarjs/prefer-read-only-props"               : 0,
		"sonarjs/prefer-regexp-exec"                   : 0,
		"sonarjs/prefer-single-boolean-return"         : 0,
		"sonarjs/prefer-type-guard"                    : 0,	// typescript
		"sonarjs/prefer-while"                         : 2,
		"sonarjs/production-debug"                     : 0,
		"sonarjs/pseudo-random"                        : 0,
		"sonarjs/public-static-readonly"               : 0,	// typescript
		"sonarjs/publicly-writable-directories"        : 0,
		"sonarjs/reduce-initial-value"                 : 2,
		"sonarjs/redundant-type-aliases"               : 0,	// typescript
		"sonarjs/regex-complexity"                     : [2, {threshold : 40}],
		"sonarjs/session-regeneration"                 : 0,
		"sonarjs/shorthand-property-grouping"          : 0,
		"sonarjs/single-char-in-character-classes"     : 2,
		"sonarjs/single-character-alternation"         : 2,
		"sonarjs/slow-regex"                           : 0,
		"sonarjs/sql-queries"                          : 0,
		"sonarjs/stable-tests"                         : 0,
		"sonarjs/stateful-regex"                       : 2,
		"sonarjs/strict-transport-security"            : 0,
		"sonarjs/strings-comparison"                   : 2,
		"sonarjs/super-invocation"                     : 2,
		"sonarjs/table-header"                         : 0,
		"sonarjs/table-header-reference"               : 0,
		"sonarjs/test-check-exception"                 : 0,
		"sonarjs/todo-tag"                             : 0,
		"sonarjs/too-many-break-or-continue-in-loop"   : 0,
		"sonarjs/unicode-aware-regex"                  : 2,
		"sonarjs/unused-import"                        : 0,	// handled by eslint
		"sonarjs/unused-named-groups"                  : 0,
		"sonarjs/unverified-certificate"               : 0,
		"sonarjs/unverified-hostname"                  : 0,
		"sonarjs/updated-const-var"                    : 2,
		"sonarjs/updated-loop-counter"                 : 2,
		"sonarjs/use-type-alias"                       : 2,	// typescript
		"sonarjs/values-not-convertible-to-numbers"    : 2,
		"sonarjs/variable-name"                        : 0,
		"sonarjs/void-use"                             : 2,
		"sonarjs/weak-ssl"                             : 0,
		"sonarjs/x-powered-by"                         : 0,
		"sonarjs/xml-parser-xxe"                       : 0,

	}
};
