import stylisticJs from "@stylistic/eslint-plugin-js";

export default
{
	plugins :
	{
		"@stylistic" : stylisticJs
	},
	rules :
	{
		// https://eslint.style/packages/js#rules
		"@stylistic/array-bracket-newline"            : 0,
		"@stylistic/array-bracket-spacing"            : [2, "never"],
		"@stylistic/array-element-newline"            : 0,
		"@stylistic/arrow-parens"                     : [2, "as-needed"],
		"@stylistic/arrow-spacing"                    : [2, {"before" : true, "after" : true}],
		"@stylistic/block-spacing"                    : 2,
		"@stylistic/brace-style"                      : [2, "allman", {"allowSingleLine" : true}],
		"@stylistic/comma-dangle"                     : [2, "never"],
		"@stylistic/comma-spacing"                    : [2, { "before" : false, "after" : true }],
		"@stylistic/comma-style"                      : [2, "last"],
		"@stylistic/computed-property-spacing"        : [2, "never"],
		"@stylistic/dot-location"                     : [2, "object"],
		"@stylistic/eol-last"                         : [2, "always"],
		"@stylistic/function-call-argument-newline"   : 0, // In Theory I like [2, "never"] here, but due to how I call tiptoe() with newlines, I have to disable this rule
		"@stylistic/function-call-spacing"            : [2, "never"],
		"@stylistic/function-paren-newline"           : [2, "consistent"],
		"@stylistic/generator-star-spacing"           : 0,
		"@stylistic/implicit-arrow-linebreak"         : 0,
		"@stylistic/indent"                           : [2, "tab", {"SwitchCase" : 1}],
		"@stylistic/jsx-quotes"                       : 0,
		"@stylistic/key-spacing"                      : [2, {"beforeColon" : true, "afterColon" : true, "mode" : "minimum"}],
		"@stylistic/keyword-spacing"                  : 0,
		"@stylistic/line-comment-position"			  : 0,
		"@stylistic/linebreak-style"                  : [2, "unix"],
		"@stylistic/lines-around-comment"             : 0,
		"@stylistic/lines-between-class-members"      : [0],
		"@stylistic/max-len"                          : 0,
		"@stylistic/max-statements-per-line"          : 0,
		"@stylistic/multiline-comment-style"          : 0,
		"@stylistic/multiline-ternary"                : [2, "never"],
		"@stylistic/new-parens"                       : 2,
		"@stylistic/newline-per-chained-call"         : 0,
		"@stylistic/no-confusing-arrow"               : [2, {"allowParens" : true}],
		"@stylistic/no-extra-parens"                  : 0,
		"@stylistic/no-extra-semi"                    : 2,
		"@stylistic/no-floating-decimal"              : 2,
		"@stylistic/no-mixed-operators"               : 2,
		"@stylistic/no-mixed-spaces-and-tabs"         : [2, "smart-tabs"],
		"@stylistic/no-multi-spaces"                  : [2, { ignoreEOLComments : true, exceptions : { VariableDeclarator : true, AssignmentExpression : true } }],
		"@stylistic/no-multiple-empty-lines"          : 2,
		"@stylistic/no-tabs"                          : 0,
		"@stylistic/no-trailing-spaces"               : [2, {"skipBlankLines" : true}],
		"@stylistic/no-whitespace-before-property"    : 2,
		"@stylistic/nonblock-statement-body-position" : [2, "below"],
		"@stylistic/object-curly-newline"             : 0,
		"@stylistic/object-curly-spacing"             : 0,
		"@stylistic/object-property-newline"          : 0,
		"@stylistic/one-var-declaration-per-line"     : 0,
		"@stylistic/operator-linebreak"               : 0,
		"@stylistic/padded-blocks"                    : [2, "never"],
		"@stylistic/padding-line-between-statements"  : 0,
		"@stylistic/quote-props"                      : 0,
		"@stylistic/quotes"                           : [2, "double", {"avoidEscape" : true, "allowTemplateLiterals" : true}],
		"@stylistic/rest-spread-spacing"              : [2, "never"],
		"@stylistic/semi"                             : [2, "always"],
		"@stylistic/semi-spacing"                     : 0,
		"@stylistic/semi-style"                       : [2, "last"],
		"@stylistic/space-before-blocks"              : [2, "always"],
		"@stylistic/space-before-function-paren"      : [2, { "anonymous" : "never", "named" : "never", "asyncArrow" : "always" }],
		"@stylistic/space-in-parens"                  : 0,
		"@stylistic/space-infix-ops"                  : 0,
		"@stylistic/space-unary-ops"                  : 2,
		"@stylistic/spaced-comment"                   : 0,
		"@stylistic/switch-colon-spacing"             : [2, {"after" : true, "before" : false}],
		"@stylistic/template-curly-spacing"           : [2, "never"],
		"@stylistic/template-tag-spacing"             : 2,
		"@stylistic/wrap-iife"                        : [2, "inside"],
		"@stylistic/wrap-regex"                       : 2,
		"@stylistic/yield-star-spacing"               : 0
	}
};
