import eslintPluginUnicorn from "eslint-plugin-unicorn";

export default
{
	plugins :
	{
		unicorn : eslintPluginUnicorn
	},
	rules :
	{
		// https://github.com/sindresorhus/eslint-plugin-unicorn#rules
		"unicorn/better-regex"                            : [2, {sortCharacterClasses : false}],
		"unicorn/catch-error-name"                        : [2, {name : "err"}],
		"unicorn/consistent-destructuring"                : 2,
		"unicorn/consistent-empty-array-spread"           : 2,
		"unicorn/consistent-existence-index-check"        : 2,
		"unicorn/consistent-function-scoping"             : 0,
		"unicorn/custom-error-definition"                 : 2,
		"unicorn/empty-brace-spaces"                      : 2,
		"unicorn/error-message"                           : 2,
		"unicorn/escape-case"                             : 2,
		"unicorn/expiring-todo-comments"                  : 0,
		"unicorn/explicit-length-check"                   : 0,
		"unicorn/filename-case"                           : 0,
		"unicorn/import-style"                            : 0,
		"unicorn/new-for-builtins"                        : 0,
		"unicorn/no-abusive-eslint-disable"               : 0,
		"unicorn/no-anonymous-default-export"             : 2,
		"unicorn/no-array-callback-reference"             : 0,
		"unicorn/no-array-for-each"                       : 0,
		"unicorn/no-array-method-this-argument"           : 0,
		"unicorn/no-array-push-push"                      : 0,
		"unicorn/no-array-reduce"                         : 0,
		"unicorn/no-await-expression-member"			  : 0,
		"unicorn/no-await-in-promise-methods"             : 2,
		"unicorn/no-console-spaces"                       : 0,
		"unicorn/no-document-cookie"                      : 2,
		"unicorn/no-empty-file"							  : 2,
		"unicorn/no-for-loop"                             : 0,
		"unicorn/no-hex-escape"                           : 2,
		"unicorn/no-instanceof-array"                     : 2,
		"unicorn/no-invalid-fetch-options"                : 2,
		"unicorn/no-invalid-remove-event-listener"        : 2,
		"unicorn/no-keyword-prefix"                       : 0,
		"unicorn/no-length-as-slice-end"                  : 2,
		"unicorn/no-lonely-if"                            : 2, // Better than the eslint base rule
		"unicorn/no-magic-array-flat-depth"               : 0,
		"unicorn/no-negated-condition"                    : 0,
		"unicorn/no-negation-in-equality-check"           : 2,
		"unicorn/no-nested-ternary"                       : 0,
		"unicorn/no-new-array"                            : 2,
		"unicorn/no-new-buffer"                           : 0,
		"unicorn/no-null"                                 : 0,
		"unicorn/no-object-as-default-parameter"          : 0,
		"unicorn/no-process-exit"                         : 0,
		"unicorn/no-single-promise-in-promise-methods"    : 2,
		"unicorn/no-static-only-class"                    : 2,
		"unicorn/no-thenable"                             : 2,
		"unicorn/no-this-assignment"                      : 0,
		"unicorn/no-typeof-undefined"                     : 2,
		"unicorn/no-unnecessary-await"                    : 2,
		"unicorn/no-unnecessary-polyfills"                : 2,
		"unicorn/no-unreadable-array-destructuring"       : 0,
		"unicorn/no-unreadable-iife"                      : 2,
		"unicorn/no-unused-properties"                    : 2,
		"unicorn/no-useless-fallback-in-spread"           : 2,
		"unicorn/no-useless-length-check"                 : 2,
		"unicorn/no-useless-promise-resolve-reject"       : 2,
		"unicorn/no-useless-spread"                       : 2,
		"unicorn/no-useless-switch-case"                  : 2,
		"unicorn/no-useless-undefined"                    : 0,
		"unicorn/no-zero-fractions"                       : 0,
		"unicorn/number-literal-case"                     : 2,
		"unicorn/numeric-separators-style"                : [2, {hexadecimal : {minimumDigits : 5, groupLength : 2}, number : {minimumDigits : 6, groupLength : 3}}],
		"unicorn/prefer-add-event-listener"               : 2,
		"unicorn/prefer-array-find"                       : 2,
		"unicorn/prefer-array-flat"                       : 2,
		"unicorn/prefer-array-flat-map"                   : 2,
		"unicorn/prefer-array-index-of"                   : 2,
		"unicorn/prefer-array-some"                       : 2,
		"unicorn/prefer-at"                               : 2,
		"unicorn/prefer-blob-reading-methods"             : 2,
		"unicorn/prefer-code-point"                       : 0,
		"unicorn/prefer-date-now"                         : 2,
		"unicorn/prefer-default-parameters"               : 2,
		"unicorn/prefer-dom-node-append"                  : 2,
		"unicorn/prefer-dom-node-dataset"                 : 0, // Only handles setAttribute. My version sembiance/prefer-dataset handles both get and set and remove
		"unicorn/prefer-dom-node-remove"                  : 2,
		"unicorn/prefer-dom-node-text-content"            : 2,
		"unicorn/prefer-event-target"                     : 2,
		"unicorn/prefer-export-from"                      : 2,
		"unicorn/prefer-global-this"                      : 0,
		"unicorn/prefer-includes"                         : 2,
		"unicorn/prefer-json-parse-buffer"                : 2,
		"unicorn/prefer-keyboard-event-key"               : 2,
		"unicorn/prefer-logical-operator-over-ternary"    : 2,
		"unicorn/prefer-math-min-max"                     : 2,
		"unicorn/prefer-math-trunc"                       : 2,
		"unicorn/prefer-modern-dom-apis"                  : 2,
		"unicorn/prefer-modern-math-apis"                 : 2,
		"unicorn/prefer-module"                           : 0,
		"unicorn/prefer-native-coercion-functions"        : 2,
		"unicorn/prefer-negative-index"                   : 2,
		"unicorn/prefer-node-protocol"                    : 0,
		"unicorn/prefer-number-properties"                : 0,
		"unicorn/prefer-object-from-entries"              : 2,
		"unicorn/prefer-optional-catch-binding"           : 0,
		"unicorn/prefer-prototype-methods"                : 2,
		"unicorn/prefer-query-selector"                   : 2,
		"unicorn/prefer-reflect-apply"                    : 2,
		"unicorn/prefer-regexp-test"                      : 2,
		"unicorn/prefer-set-has"                          : 0,
		"unicorn/prefer-spread"                           : 0, // Array.from() is better as it has a mapFn built in and is covered by array-func/prefer-array-from
		"unicorn/prefer-set-size"                         : 2,
		"unicorn/prefer-string-raw"                       : 0,
		"unicorn/prefer-string-replace-all"               : 0,
		"unicorn/prefer-string-slice"                     : 0,
		"unicorn/prefer-string-starts-ends-with"          : 2,
		"unicorn/prefer-string-trim-start-end"            : 2,
		"unicorn/prefer-structured-clone"                 : 0,
		"unicorn/prefer-switch"                           : [2, {minimumCases : 4, emptyDefaultCase : "no-default-case"}],
		"unicorn/prefer-ternary"                          : 2,
		"unicorn/prefer-top-level-await"                  : 2, // No idea if I really want this set or not, since I don't use await yet and not sure how it functions
		"unicorn/prefer-type-error"                       : 2,
		"unicorn/prevent-abbreviations"                   : 0,
		"unicorn/relative-url-style"                      : 2,
		"unicorn/require-array-join-separator"            : 2,
		"unicorn/require-number-to-fixed-digits-argument" : 2,
		"unicorn/require-post-message-target-origin"      : 0,
		"unicorn/string-content"                          : 0,
		"unicorn/switch-case-braces"                      : 0,
		"unicorn/template-indent"                         : 0,
		"unicorn/text-encoding-identifier-case"           : 0,
		"unicorn/throw-new-error"                         : 2
	}
};
